"""V1.1

Revision ID: 0f9f7bdb9bcc
Revises: 51a55cd536d2
Create Date: 2025-06-28 16:06:36.721648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9f7bdb9bcc'
down_revision: Union[str, None] = '51a55cd536d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_session', schema=None) as batch_op:
        batch_op.alter_column('request_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('execution_session', schema=None) as batch_op:
        batch_op.alter_column('request_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
