"""V1

Revision ID: 4eb54baaed34
Revises: 
Create Date: 2025-03-21 07:37:54.404052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb54baaed34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('client_type_handler', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_handler', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('run_options',
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('polling', sa.Boolean(), nullable=False),
    sa.Column('polling_interval', sa.Integer(), nullable=False),
    sa.Column('delayed_start', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_handler', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('collection',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('run_options_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_handler', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.item_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['request.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['collection.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_options_id'], ['run_options.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('modbus_rtu_client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('com_port', sa.String(), nullable=False),
    sa.Column('baudrate', sa.Integer(), nullable=False),
    sa.Column('parity', sa.String(), nullable=False),
    sa.Column('stopbits', sa.Integer(), nullable=False),
    sa.Column('bytesize', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_handler', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('modbus_tcp_client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('host', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_handler', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('collection_result',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('total_ok', sa.Integer(), nullable=False),
    sa.Column('total_failed', sa.Integer(), nullable=False),
    sa.Column('total_pending', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('elapsed_time', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_handler', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['collection_result.item_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['collection.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('modbus_request',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('function', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('slave', sa.Integer(), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('run_options_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_handler', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.item_id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['request.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['collection.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_options_id'], ['run_options.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('modbus_response',
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('slave', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('function_code', sa.Integer(), nullable=True),
    sa.Column('address', sa.Integer(), nullable=True),
    sa.Column('registers', sa.JSON(), nullable=True),
    sa.Column('crc', sa.Integer(), nullable=True),
    sa.Column('raw_packet_recv', sa.String(), nullable=False),
    sa.Column('raw_packet_send', sa.String(), nullable=False),
    sa.Column('data_type', sa.String(), nullable=False),
    sa.Column('byte_count', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('client_type', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('elapsed_time', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('item_handler', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['collection_result.item_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['modbus_request.item_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('modbus_response')
    op.drop_table('modbus_request')
    op.drop_table('collection_result')
    op.drop_table('modbus_tcp_client')
    op.drop_table('modbus_rtu_client')
    op.drop_table('collection')
    op.drop_table('run_options')
    op.drop_table('client')
    # ### end Alembic commands ###
